# Generated by Django 5.1.6 on 2025-03-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='violation_app.violation'),
        ),
    ]
