# Generated by Django 5.1.6 on 2025-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_app', '0004_uploadedimage_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='detected_image',
        ),
        migrations.AddField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violation_images/'),
        ),
    ]
